# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SQL-SyntaxModel
version:      0.40
version_from: lib/SQL/SyntaxModel.pm
installdirs:  site
requires:
    Locale::KeyedText:             0.06

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
